### ISSUE TITLE
Statistical Testing For Sequencing Results

### ISSUE THREAD

**Issue by dkohlsdorf** [dkohlsdorf/wdp-ds#65]
Compare two or more contexts:
+ [x] Make sure we have strings for all codings
+ [x] Make sure we can identify the context

Statistics:
+ [x] l1 types + ngrams
+ [x] l2 types + ngrams

Visualization:
+ [x] L1 decoder start / stop
+ [x] L2 decoder start / stop
+ [x] Combine N-grams
+ [x] Pattern importance
+ [x] Export

**Comment by dkohlsdorf** [comment]
![feature_count](https://user-images.githubusercontent.com/1425435/140624159-1889a184-a292-4d6e-8814-c7f3dd1c763e.png)
