### ISSUE TITLE
Statistics Integration and Visualisation

### ISSUE THREAD

**Issue by dkohlsdorf** [dkohlsdorf/wdp-ds#69]
![feature_count](https://user-images.githubusercontent.com/1425435/140624109-10a9228d-3dae-45a3-bc93-9338ae6aa030.png)

+ [ ] Integrate Statistics (Xi - Square) and Histograms 
+ [ ] Integrate start and stop for **L1** decoder
+ [ ] integrate start and stop for **L2** decoder
