### ISSUE TITLE
Refactor Gaps

### ISSUE THREAD

**Issue by dkohlsdorf** [dkohlsdorf/wdp-ds#76]
# TODO

+ [x] Add null labels back in [here](https://github.com/dkohlsdorf/wdp-ds/blob/a94683014bb4005c3353a7b87db967a79682e0c7/lib_dolphin/sequential.py#L32)
+ [x] Make sure the plots still work [here](https://github.com/dkohlsdorf/wdp-ds/blob/a94683014bb4005c3353a7b87db967a79682e0c7/lib_dolphin/sequential.py#L51)
+ [x] Use this function [here](https://github.com/dkohlsdorf/wdp-ds/blob/a94683014bb4005c3353a7b87db967a79682e0c7/lib_dolphin/sequential.py#L85)

Maybe test using notebook.
